### ISSUE TITLE
No license available

### ISSUE THREAD

**Issue by Miepee** [biosp4rk/mzmr#1]
Since there is no license available, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation.
Please add a license, so users and developers know what they can do with the software

For more info, you can also checkout https://choosealicense.com/no-permission/

Note that since there is more than one author of this software, adding a new license means getting permission from every contributor.

**Comment by biosp4rk** [comment]
43ed51e
